### ISSUE TITLE
Gogs not kicking off builds automatically

### ISSUE THREAD

**Issue by jim-minter** [CICD-Demo/CICD-Demo#4]
@caracan you spotted this.  It's because I've hacked Gogs to call the webhook automatically, and a mixture of expiry of /v1beta1 URL endpoints + increased security means it's not working.  Workaround for now, manually kick off the builds.  I'll take a look at it.

**Comment by caracan** [comment]
FYI : Updating the webhooks from the internal cluster names to the external routes means they work. Not sure how to automate this in the gogs source.

**Comment by jim-minter** [comment]
Patch to https://github.com/CICD-Demo/gogs-src and rebuild & push docker image - FWIW see the last 3 commits to gogs-src to get the lie of the land.
Build & push is a pain, I can pick that up when I have a moment.

**Comment by jim-minter** [comment]
finally fixed it.
